# Generated by Django 4.2 on 2024-01-12 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIG', 'High')], default='LOW', max_length=3)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('FEA', 'Feature'), ('TAS', 'Task')], default='BUG', max_length=3)),
                ('status', models.CharField(choices=[('TDO', 'To do'), ('INP', 'In progress'), ('FIN', 'FInished')], default='TDO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('ios', 'Ios'), ('android', 'Android')], default='backend', max_length=10)),
            ],
        ),
    ]
