# Generated by Django 4.2 on 2024-01-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_contributor_author_alter_contributor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
