# Generated by Django 4.2 on 2024-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('can_be_contacted', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
                ('can_data_be_shared', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3)),
            ],
        ),
    ]
